# 1. Import Dependencies

In [1]:
# !conda install pytorch torchvision torchaudio cpuonly -c pytorch

In [1]:
import gym
from stable_baselines3 import A2C, PPO
from stable_baselines3.common.vec_env import VecFrameStack, DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os

C:\Users\iDLaber\miniconda3\envs\baselines\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# 2. Test Environment

In [3]:
#http://www.atarimania.com/roms/roms.rar

In [4]:
!python -m atari.py.import_roms .\ROMS

C:\Users\iDLaber\anaconda3\python.exe: Error while finding module specification for 'atari.py.import_roms' (ModuleNotFoundError: No module named 'atari')


In [5]:
environment_name = 'Breakout-v0'
env = gym.make(environment_name)

In [6]:
env.reset()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [7]:
env.action_space

Discrete(4)

In [8]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [4]:
episodes=5
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render(mode='rgb_array')
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episode:{} Score:{}'.format(episode, score))

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

In [10]:
env.close()

# 3. Vectorize Environment and Train Model

In [2]:
env = make_atari_env('Breakout-v0', n_envs=1, seed=0)
env = DummyVecEnv([lambda:env])
log_path = os.path.join('Training','Logs')
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log = log_path)
# MlpPolicy: Dense NN

Using cpu device
Wrapping the env in a VecTransposeImage.


In [3]:
# log_path = os.path.join('Training','Logs')
# model=A2C('CnnPolicy', env, verbose=1, tensorboard_log=log_path)

MlpPolicy: Tabular Data -> good
CnnPolicy: Image Data -> good

In [15]:
model.learn(total_timesteps=10000)

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

# 4. Save and Reload Model

In [ ]:
a2c_path = os.path.join('Training','Saved Models','A2C_Breakout_Model')
model.save(a2c_path)

In [ ]:
del model

In [ ]:
model = A2C.load(a2c_path, env)

# 5. Evaluate and Test

In [ ]:
env = make_atari_env('Breakout-v0', n_envs=1, seed=0)
env = VecFrameStack(env, n_stack=4)

In [ ]:
evaluate_policy(model=model,env=env, n_eval_episodes=10, render=True)
# fail -> it is based on one policy evaluation
# Therefore need to change the env into the 1 env

In [ ]:
env.close()